name = "bots-lilnouns-settler"
main = "src/index.ts"
compatibility_date = "2022-06-29"
account_id = "4705ffc1b2306b394e91eeda4a7a150a"
usage_model = "bundled"
workers_dev = true

[triggers]
crons = ['* * * * *']

[vars]
LAG_PERIOD = 15
RPC = 'https://rpc.ankr.com/eth/'
WKEY = ''

[env.prod]
name = "prod-bots-lilnouns-settler"

[env.prod.vars]
LAG_PERIOD = 15
